Repository skylines-project/skylines, pull requests merged in 2018-05, with the labels that each got.

#836 Add basic tests for `Notification` code
  skylines/api/views/clubs.py
  skylines/api/views/flights.py
  skylines/api/views/settings.py
  skylines/api/views/upload.py
  skylines/api/views/users.py
  skylines/model/__init__.py
  skylines/model/event.py
  skylines/model/notification.py
  tests/api/views/notifications/__init__.py
  tests/api/views/notifications/clear_test.py
  tests/api/views/timeline/list_test.py
  tests/data/events.py
Labels: internal

#837 Update `sqlalchemy` to v1.2.7
  Pipfile
  Pipfile.lock
  skylines/api/views/search.py
  skylines/api/views/statistics.py
  skylines/model/notification.py
  skylines/model/search.py
  skylines/model/user.py
  tests/api/oauth/conftest.py
  tests/api/views/flights/read_test.py
  tests/api/views/users/read_test.py
  tests/data/aircraft_models.py
  tests/data/flight_comments.py
  tests/data/flights.py
  tests/data/igcs.py
  tests/data/users.py
  tests/lib/test_sql.py
  tests/model/test_search.py
Labels: api, dependencies

#839 Fix `RefreshToken` foreign key
  migrations/versions/70a6f5e6f0e1_fix_refreshtoken_foreign_key.py
  skylines/model/oauth.py
  tests/model/test_oauth.py
Labels: bug

#849 scripts: Fix error handling for command users.merge
  skylines/commands/users/merge.py
Labels: bug

#862 Disable optional `application-template-wrapper` feature
  ember/config/optional-features.json
  ember/package.json
  ember/yarn.lock
Labels: frontend, internal

#863 Enabled optional `template-only-glimmer-components` feature
  ember/app/templates/components/cruise-performance-table.hbs
  ember/app/templates/components/flight-leg-panel.hbs
  ember/app/templates/components/flight-leg-table.hbs
  ember/app/templates/components/flight-page.hbs
  ember/app/templates/components/flight-performance-panel.hbs
  ember/app/templates/components/follower-list.hbs
  ember/app/templates/components/follower-page.hbs
  ember/app/templates/components/following-page.hbs
  ember/app/templates/components/form-page.hbs
  ember/app/templates/components/search-result-table.hbs
  ember/app/templates/components/tracking-pilots-list.hbs
  ember/app/templates/components/user-distance-flights.hbs
  ember/app/templates/components/user-page.hbs
  ember/config/optional-features.json
Labels: frontend, internal

#840 Add "Delete User" button
  ember/app/components/settings-panels/delete-account.js
  ember/app/services/notifications.js
  ember/app/templates/components/nav-bar-menu-right.hbs
  ember/app/templates/components/nav-bar-user-menu.hbs
  ember/app/templates/components/nav-bar.hbs
  ember/app/templates/components/settings-panels/delete-account.hbs
  ember/app/templates/components/validated-block.hbs
  ember/app/templates/components/validated-input.hbs
  ember/app/templates/settings/profile.hbs
  ember/tests/acceptance/settings/delete-account-test.js
  ember/translations/de.yaml
  ember/translations/en.yaml
  skylines/api/views/__init__.py
  skylines/api/views/account.py
  skylines/api/views/users.py
  skylines/model/user.py
  tests/api/views/account/__init__.py
  tests/api/views/account/delete_test.py
  tests/api/views/users/delete_test.py
  tests/data/igcs.py
  tests/model/test_user.py
Labels: api, enhancement, frontend, high-priority

#864 Fix search including unicode characters
  skylines/model/search.py
  tests/api/views/search_test.py
Labels: api, bug

#865 Load Intl.js polyfill conditionally on app startup
  ember/app/index.html
  ember/app/routes/application.js
  ember/app/services/intl.js
  ember/package.json
  ember/yarn.lock
Labels: enhancement, frontend

#694 Update installation notes
  INSTALL.mapserver.md
  INSTALL.md
Labels: documentation

#867 Move `.editorconfig` file to the top-level folder
  .editorconfig
Labels: internal

#871 Add `tracking delete-old` command
  skylines/commands/tracking/__init__.py
  skylines/commands/tracking/delete_old.py
Labels: enhancement

#873 components/comments-list: Fix table width and word wrapping
  ember/app/templates/components/comments-list.hbs
Labels: bug, frontend

#874 commands/airspace: Remove broken `ReadingError` import
  skylines/commands/import_/airspace.py
Labels: internal

#868 Add `PRIVACY.md` document
  PRIVACY.md
  ember/app/templates/components/base-page.hbs
  ember/translations/de.yaml
  ember/translations/en.yaml
Labels: documentation, high-priority

#887 Update `iltorb` subdependency
  ember/yarn.lock
Labels: frontend, internal

#888 privacy policy: fix information regarding email address when creating an account
  PRIVACY.md
Labels: documentation, high-priority

#891 Remove obsolete `start/destroy-app` test helpers
  ember/tests/helpers/destroy-app.js
  ember/tests/helpers/start-app.js
Labels: frontend, internal

#889 Add `users email` command
  config/default.py
  skylines/commands/users/__init__.py
  skylines/commands/users/email.py
Labels: internal

#894 Add `ember-freestyle` component playground
  ember/app/router.js
  ember/app/templates/application.hbs
  ember/ember-cli-build.js
  ember/lib/.eslintrc.js
  ember/lib/freestyle/app/controllers/freestyle.js
  ember/lib/freestyle/app/routes/freestyle.js
  ember/lib/freestyle/app/templates/components/usage/x-flag.hbs
  ember/lib/freestyle/app/templates/freestyle.hbs
  ember/lib/freestyle/index.js
  ember/lib/freestyle/package.json
  ember/package.json
  ember/yarn.lock
Labels: frontend, internal

#902 Pipfile: Add `manage` script
  Pipfile
Labels: internal

#903 CI: Prevent `dependabot` branches from building twice
  .travis.yml
Labels: internal

#904 Improve Vagrant environment
  Vagrantfile
Labels: internal
