Repository skylines-project/skylines, pull requests merged in 2018-03, with the labels that each got.

#728 Update gevent package
  setup.py
Labels: internal

#740 Replace `fake-factory` dependency with `Faker`
  requirements.txt
Labels: api, internal

#724 Update `xcsoar` to v0.6.1
  setup.py
Labels: internal

#759 Use `print()` function instead of deprecated `print` keyword
  migrations/versions/46434b0a4c10_split_user_name_into.py
  skylines/commands/__init__.py
  skylines/commands/aircraft.py
  skylines/commands/flights/analysis.py
  skylines/commands/flights/copy_flights.py
  skylines/commands/flights/delete_flights.py
  skylines/commands/flights/find_meetings.py
  skylines/commands/flights/selector.py
  skylines/commands/flights/update_flight_paths.py
  skylines/commands/import_/airspace.py
  skylines/commands/import_/mwp.py
  skylines/commands/import_/srtm.py
  skylines/commands/import_/welt2000.py
  skylines/commands/search.py
  skylines/commands/tracking/clear.py
  skylines/commands/tracking/export.py
  skylines/commands/tracking/generate.py
  skylines/commands/tracking/generate_through_daemon.py
  skylines/commands/tracking/server.py
  skylines/commands/tracking/stats.py
  skylines/commands/users/merge.py
  skylines/tracking/server.py
  tests/api/views/airports/read_test.py
  tests/data/bootstrap.py
  tests/test_flake8.py
Labels: api, internal

#760 Replace Mocha/Chai with QUnit
  ember/package.json
  ember/tests/.eslintrc.js
  ember/tests/acceptance/index-test.js
  ember/tests/acceptance/login-test.js
  ember/tests/acceptance/page-not-found-test.js
  ember/tests/acceptance/upload-test.js
  ember/tests/helpers/setup-acceptance-test.js
  ember/tests/helpers/setup-pretender.js
  ember/tests/integration/components/flight-list-nav-test.js
  ember/tests/integration/components/timeline-events/club-join-test.js
  ember/tests/integration/components/timeline-events/flight-comment-test.js
  ember/tests/integration/components/timeline-events/flight-upload-test.js
  ember/tests/integration/components/timeline-events/follower-test.js
  ember/tests/integration/components/timeline-events/new-user-test.js
  ember/tests/test-helper.js
  ember/tests/unit/helpers/initials-test.js
  ember/tests/unit/services/map-settings-test.js
  ember/tests/unit/utils/add-days-test.js
  ember/tests/unit/utils/parse-query-string-test.js
  ember/yarn.lock
Labels: frontend, internal
