Repository skylines-project/skylines, pull requests merged in 2018-04, with the labels that each got.

#769 Update supervisor configuration
  supervisor/mapproxy.conf
  supervisor/mapserver.conf
  supervisor/skylines-api.conf
  supervisor/skylines.conf
  uwsgi/skylines-api.ini
  uwsgi/skylines-api.py
Labels: api, internal

#770 Fix MapServer configuration
  mapserver/airports/airports.map
  mapserver/fonts/truetype.txt
Labels: bug, data

#663 update airspace files to more recent versions
  mapserver/airspace/airspace_blacklist.txt
  mapserver/airspace/airspace_list.txt
Labels: data, enhancement

#793 sentry: Share only user ID as user context
  ember/app/routes/application.js
Labels: frontend, internal

#795 utils/flight-collection: Fix array content observers
  ember/app/utils/flight-collection.js
Labels: frontend, internal

#798 api/flights: Remove unused "latest" parameter
  skylines/api/views/flights.py
Labels: api, internal

#803 Use `pipenv` for backend dependency management
  .gitignore
  .travis.yml
  INSTALL.md
  Pipfile
  Pipfile.lock
  Vagrantfile
  requirements.txt
  setup.py
Labels: api, internal

#804 Update `werkzeug` to v0.14.1
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#806 Update `flask-sqlalchemy` to v2.3.2
  Pipfile
  Pipfile.lock
  config/default.py
Labels: api, dependencies

#807 Update `oauthlib` and `flask-oauthlib` dependencies
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#808 Update `geoalchemy2` to v0.4.2
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#810 Update `alembic` and `flask-migrate` dependencies
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#811 Update `flask-cache` to v0.13.1
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#812 Update `flask` to 1.0
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#813 Update `webargs` to v2.1.0
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#814 Add `mapproxy` dependency
  Pipfile
  Pipfile.lock
Labels: api, dependencies

#815 Use `http` protocol for `uwsgi`
  uwsgi/mapproxy.ini
  uwsgi/mapserver.ini
  uwsgi/skylines.ini
Labels: api, internal

#816 supervisor/mapserver: Run outside of the virtualenv
  supervisor/mapserver.conf
Labels: internal

#829 Replace unmaintained `flask-cache` with `flask-caching`
  Pipfile
  Pipfile.lock
  skylines/api/cache.py
Labels: api, dependencies
